name: roman
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytables
  - numpy
  - pandas
  - tenacity
  - sqlalchemy<2
  - mysql-connector-python
  - mysqlclient
  - astropy
  - jinja2
  - pip
  - pip:
      - pymysql
