from django.test import TestCase, override_settings


@override_settings(
    ST123_BASE_DIR='/data/ckilpatrick/HST/2026dix',
    ST123_TARGET_NAME='2026dix',
    ST123_CAMPAIGN_REGISTRY='/tmp/pipelinesite-missing-campaign-targets.json',
)
class CampaignPageTests(TestCase):
    def test_home_and_target_pages_render(self):
        home = self.client.get('/')
        self.assertEqual(home.status_code, 200)
        self.assertContains(home, 'SN 2026dix')
        self.assertContains(home, '18338')
        self.assertContains(home, 'stsci.edu/hst-program-info/program/?program=18338')
        self.assertNotContains(home, 'HST example field')
        self.assertContains(home, 'NGC 3913')
        self.assertNotContains(home, 'IIb')
        self.assertContains(home, 'GLADE+')
        self.assertNotContains(home, 'Dispatch')
        self.assertNotContains(home, '>Target</a>')
        self.assertContains(home, 'Search targets')
        self.assertContains(home, 'NGC 1494')
        self.assertContains(home, 'NGC 784')
        self.assertContains(home, 'Jobs')
        self.assertContains(home, '/ 1 running')
        target = self.client.get('/manager/targets/2026dix')
        self.assertEqual(target.status_code, 200)
        self.assertContains(target, 'Images')
        self.assertContains(target, 'Catalogs')
        self.assertContains(target, 'Host')
        self.assertContains(target, 'NGC 3913')
        self.assertNotContains(target, 'IIb')
        self.assertContains(target, 'Reference image')
        self.assertContains(target, 'WFC3')
        self.assertContains(target, 'F625W')
        self.assertContains(target, 'Download HDF5')
        self.assertContains(target, 'Download mosaic')
        self.assertContains(target, 'data-reference-select')
        self.assertContains(target, 'WFC3 F625W (DOLPHOT reference)')
        self.assertContains(target, 'Quality DOLPHOT sources')
        self.assertContains(target, 'Quality-cut DOLPHOT sources')
        self.assertContains(target, 'Gaia alignment sources')
        self.assertContains(target, 'Gaia stars used for absolute WCS')
        self.assertNotContains(target, 'Science frames under')
        self.assertNotContains(target, 'Reference image + sources')
        self.assertNotContains(target, 'Scroll to zoom')
        self.assertNotContains(target, 'HST example field')
        self.assertContains(target, '11m')
        self.assertNotContains(target, '>Target</a>')
        self.assertNotContains(target, '+00:00')
        self.assertContains(target, '2 × 4096 × 2051')
        self.assertContains(target, '4 × 800 × 800')

    def test_target_search_redirects(self):
        resp = self.client.get('/manager/search', {'q': '2026dix'})
        self.assertEqual(resp.status_code, 302)
        home = self.client.get('/', {'q': '2026dix'})
        self.assertEqual(home.status_code, 302)
        self.assertIn('/manager/targets/2026dix', home['Location'])
        ngc = self.client.get('/', {'q': 'NGC 1494'})
        self.assertEqual(ngc.status_code, 302)
        self.assertIn('/manager/targets/ngc1494', home['Location'])
        ngc784 = self.client.get('/', {'q': 'NGC 784'})
        self.assertEqual(ngc784.status_code, 302)
        self.assertIn('/manager/targets/ngc784', home['Location'])

    def test_ngc1494_target_page_renders(self):
        page = self.client.get('/manager/targets/ngc1494')
        self.assertEqual(page.status_code, 200)
        self.assertContains(page, 'NGC 1494')
        self.assertContains(page, '/data/ckilpatrick/HST/ngc1494')
        self.assertContains(page, 'data-dispatch-message')
        self.assertContains(page, 'data-dispatch-allowed')

    def test_ngc784_target_page_renders(self):
        page = self.client.get('/manager/targets/ngc784')
        self.assertEqual(page.status_code, 200)
        self.assertContains(page, 'NGC 784')
        self.assertContains(page, '/data/ckilpatrick/HST/ngc784')
        self.assertContains(page, 'data-dispatch-allowed')
        self.assertContains(page, 'data-reference-select')
        self.assertContains(page, 'ACS F814W (DOLPHOT reference)')
        self.assertContains(page, 'ACS F606W')
        self.assertContains(page, 'WFPC2 F606W')
        self.assertContains(page, 'WFPC2 F814W')
        self.assertNotContains(page, 'align prelim')
        self.assertContains(page, 'Download mosaic')
        self.assertContains(page, 'Download HDF5')
