from django.contrib.auth import get_user_model
from django.test import TestCase, override_settings


@override_settings(
    ST123_BASE_DIR='/data/ckilpatrick/HST/2026dix',
    ST123_TARGET_NAME='2026dix',
    ST123_CAMPAIGN_REGISTRY='/tmp/pipelinesite-missing-campaign-targets.json',
    ST123_DATA_ROOT='/tmp/pipelinesite-missing-data',
)
class CampaignPageTests(TestCase):
    def setUp(self):
        user = get_user_model().objects.create_user('viewer', password='secret')
        self.client.force_login(user)

    def test_home_and_target_pages_render(self):
        home = self.client.get('/')
        self.assertEqual(home.status_code, 200)
        self.assertContains(home, 'Programs')
        self.assertContains(home, 'GO 18338')
        self.assertContains(home, 'GO 18440')
        self.assertContains(home, 'Completing a Legacy Dataset')
        self.assertContains(home, 'Catch Them While They')
        self.assertContains(home, 'Charles Kilpatrick')
        self.assertContains(home, 'Maria Drout')
        self.assertContains(home, 'stsci.edu/hst-program-info/program/?program=18338')
        self.assertContains(home, 'stsci.edu/hst-program-info/program/?program=18440')
        self.assertContains(home, 'Search targets')
        self.assertContains(home, 'viewer')
        self.assertNotContains(home, '>Admin<')
        self.assertNotContains(home, 'HST example field')
        campaign = self.client.get('/programs/18338')
        self.assertEqual(campaign.status_code, 200)
        self.assertContains(campaign, 'NGC 157')
        self.assertContains(campaign, 'NGC 157 parallel')
        self.assertContains(campaign, 'NGC 7814')
        self.assertContains(campaign, '>Prime<')
        self.assertContains(campaign, '>Parallel<')
        self.assertContains(campaign, 'Jobs')
        self.assertContains(campaign, '/ 1 running')
        self.assertNotContains(campaign, 'SN 2026dix')
        self.assertNotContains(campaign, 'NGC 4157')
        self.assertNotContains(campaign, 'IIb')
        self.assertNotContains(campaign, 'Dispatch')
        target = self.client.get('/manager/targets/2026dix')
        self.assertEqual(target.status_code, 200)
        self.assertContains(target, 'Images')
        self.assertContains(target, 'Date/Time')
        self.assertContains(target, 'data-sortable')
        self.assertNotContains(target, '>Product</th>')
        self.assertContains(target, '2024-01-25T')
        self.assertContains(target, 'Catalogs')
        self.assertContains(target, 'Host')
        self.assertContains(target, 'NGC 3913')
        self.assertNotContains(target, 'IIb')
        self.assertContains(target, 'Reference image')
        self.assertContains(target, 'WFC3')
        self.assertContains(target, 'F625W')
        self.assertContains(target, 'Download HDF5')
        self.assertContains(target, 'Download mosaic')
        self.assertContains(target, 'data-reference-select')
        self.assertContains(target, 'WFC3 F625W')
        self.assertContains(target, 'DOLPHOT reference')
        self.assertContains(target, 'Quality DOLPHOT sources')
        self.assertContains(target, 'Quality-cut DOLPHOT sources')
        self.assertContains(target, 'Gaia alignment sources')
        self.assertContains(target, 'Gaia stars used for absolute WCS')
        self.assertNotContains(target, 'Science frames under')
        self.assertNotContains(target, 'Reference image + sources')
        self.assertNotContains(target, 'Scroll to zoom')
        self.assertNotContains(target, 'HST example field')
        self.assertContains(target, '11m')
        self.assertNotContains(target, '>Target</a>')
        self.assertNotContains(target, '+00:00')
        self.assertContains(target, '2 × 4096 × 2051')
        self.assertContains(target, '4 × 800 × 800')

    def test_target_search_redirects(self):
        home = self.client.get('/', {'q': 'ngc7814'})
        self.assertEqual(home.status_code, 302)
        self.assertIn('/manager/targets/ngc7814', home['Location'])
        both = self.client.get('/', {'q': 'NGC 157'})
        self.assertEqual(both.status_code, 200)
        self.assertContains(both, 'NGC 157')
        self.assertContains(both, 'NGC 157 parallel')
        par = self.client.get('/', {'q': 'ngc0157par'})
        self.assertEqual(par.status_code, 302)
        self.assertIn('/manager/targets/ngc0157par', par['Location'])

    def test_ngc0157_prime_and_parallel_pages(self):
        prime = self.client.get('/manager/targets/ngc0157')
        self.assertEqual(prime.status_code, 200)
        self.assertContains(prime, 'NGC 157')
        self.assertContains(prime, '>Prime<')
        self.assertContains(prime, '/data/ckilpatrick/go18338/ngc0157')
        self.assertContains(prime, 'data-dispatch-message')
        self.assertContains(prime, 'data-dispatch-allowed')
        parallel = self.client.get('/manager/targets/ngc0157par')
        self.assertEqual(parallel.status_code, 200)
        self.assertContains(parallel, 'NGC 157 parallel')
        self.assertContains(parallel, '>Parallel<')
        self.assertContains(parallel, '/data/ckilpatrick/go18338/ngc0157par')
        self.assertNotContains(parallel, '/data/ckilpatrick/HST/ngc0157')

    def test_program_18440_campaign_lists_apt_targets(self):
        page = self.client.get('/programs/18440')
        self.assertEqual(page.status_code, 200)
        self.assertContains(page, 'GO 18440')
        self.assertContains(page, 'Catch Them While They')
        self.assertContains(page, 'Maria Drout')
        self.assertContains(page, 'stsci.edu/hst-program-info/program/?program=18440')
        self.assertContains(page, 'IC 1954')
        self.assertContains(page, 'NGC 247')
        self.assertContains(page, 'NGC 1291-1')
        self.assertNotContains(page, 'No targets yet.')
        self.assertNotContains(page, 'SN 2026dix')
        self.assertNotContains(page, 'NGC 157')
        target = self.client.get('/manager/targets/ic1954')
        self.assertEqual(target.status_code, 200)
        self.assertContains(target, '/data/ckilpatrick/go18440/ic1954')

    def test_legacy_campaign_url_redirects_to_18338(self):
        resp = self.client.get('/manager/campaign')
        self.assertEqual(resp.status_code, 302)
        self.assertIn('/programs/18338', resp['Location'])
