# Install the package and run tests on every push and on PRs into main.
name: WINGS

on:
  push:
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    services:
      mysql:
        image: mysql:5.7.29
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: server
        ports:
          - 8000:3306
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[test,docs,demo]"
          python -m pip install pymysql
          mkdir ./temp
      - name: Run unit tests
        env:
          PIPELINESITE_DEMO: '1'
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/wings/src:${{ github.workspace }}/wings/src/pipelinesite
        run: python wings/src/pipelinesite/manage.py test tests
      - name: Attempt to run wingspipe
        run: |
          cd ./temp
          wingspipe --github-test
      - name: Build documentation
        run: make html
        working-directory: docs
